apiVersion: v1
kind: ConfigMap

metadata:
  name: frontend-nginx-config

data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            location / {
                return 200 'Hello from ConfigMap YAML!\n';
                add_header Content-Type text/plain;
            }

            location /api {
                proxy_pass http://backend-service;
            }
        }
    }