apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 4

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: flexiblekim/openstream-backend:0e91d9feb5d06d7226b4bf4dd3ae33d7d43a8887
          ports:
            - containerPort: 5678